// examples/vue/src/wallet-connection.vue
<script setup lang="ts">
import {
  useConnectedWallets,
  useWalletConnector,
  useWalletDisconnector,
  useWallets,
} from "@reactive-dot/vue";

const { data: wallets } = await useWallets();
const { data: connectedWallets } = await useConnectedWallets();
const { execute: connect, status: connectStatus } = useWalletConnector();
const { execute: disconnect, status: disconnectStatus } =
  useWalletDisconnector();
</script>

<template>
  <section>
    <h3>Wallet connection</h3>
  </section>
  <article>
    <h4>Wallets</h4>
    <ul>
      <li v-for="wallet in wallets" :key="wallet.id">
        {{ wallet.name }}:
        <button
          v-if="!connectedWallets.includes(wallet)"
          :disabled="
            connectStatus === 'pending' || disconnectStatus === 'pending'
          "
          @click="connect(wallet)"
        >
          Connect
        </button>
        <button
          v-if="connectedWallets.includes(wallet)"
          :disabled="
            connectStatus === 'pending' || disconnectStatus === 'pending'
          "
          @click="disconnect(wallet)"
        >
          Disconnect
        </button>
      </li>
    </ul>
  </article>
</template>

// examples/react/src/wallet-connection.tsx
import { pending } from "@reactive-dot/core";
import type { Wallet } from "@reactive-dot/core/wallets.js";
import {
  useConnectedWallets,
  useWalletConnector,
  useWalletDisconnector,
  useWallets,
} from "@reactive-dot/react";

export function WalletConnection() {
  const wallets = useWallets();

  return (
    <section>
      <header>
        <h3>Wallet connection</h3>
      </header>
      <article>
        <h4>Wallets</h4>
        <ul>
          {wallets.map((wallet) => (
            <WalletItem key={wallet.id} wallet={wallet} />
          ))}
        </ul>
      </article>
    </section>
  );
}

type WalletItemProps = {
  wallet: Wallet;
};

function WalletItem({ wallet }: WalletItemProps) {
  const connectedWallets = useConnectedWallets();

  const [connectingState, connect] = useWalletConnector(wallet);
  const [disconnectingState, disconnect] = useWalletDisconnector(wallet);

  return (
    <li>
      {wallet.name}:{" "}
      {connectedWallets.includes(wallet) ? (
        <button
          type="button"
          onClick={() => disconnect()}
          disabled={disconnectingState === pending}
        >
          Disconnect{disconnectingState === pending && <>...</>}
        </button>
      ) : (
        <button
          type="button"
          onClick={() => connect()}
          disabled={connectingState === pending}
        >
          Connect{connectingState === pending && <>...</>}
        </button>
      )}
    </li>
  );
}
